services:
  freeradius:
    image: freeradius/freeradius-server:latest
    container_name: freeradius
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env.radius
    volumes:
      - ./raddb:/etc/freeradius:ro
      - ./certs:/etc/freeradius/certs:ro
    command:
      - -f
      - -lstdout
